name: happy_dish
description: Happy Dish - What to eat?
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true
  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
  assets:
    - assets/images/android12splash.png
