name: happy_dish
description: Happy Dish - What to eat?
publish_to: "none"
version: 2.0.0+3

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  audioplayers: ^5.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10
  vibration: ^1.8.1

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.5.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.1.4
  riverpod_lint: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
  assets:
    - assets/images/android12splash.png
    - assets/images/home-illustration.png
    - assets/sounds/
