class PopularDishes {
  static const List<String> internationalDishes = [
    "Spaghetti Carbonara",
    "Chicken Teriyaki",
    "Pizza",
    "Sushi",
    "Caesar Salad",
    "Fish and Chips",
    "Tacos",
    "Ramen Noodles",
    "Pad Thai",
    "Butter Chicken",
    "Bangers and Mash",
    "Croque Monsieur",
    "Falafel Wrap",
    "Beef Burger",
    "Pho",
    "Chicken Curry",
    "Biryani",
    "Bratwurst",
    "Shepherd's Pie",
    "Tom Yum Goong",
    "Kebab",
    "Tempura",
    "Goulash Soup",
    "Tikka Masala",
    "BBQ Ribs",
    "Buffalo Wings",
    "Clam Chowder",
    "Lobster Roll",
    "Cheesesteak",
    "Macaroni and Cheese",
    "Pancakes",
    "Hot Dog",
    "Tex-Mex Chili",
    "Cornbread",
    "Fried Chicken",
  ];
}
